### ISSUE TITLE
MWA triggers on Swift events when star-tracker has lost lock

### ISSUE THREAD

**Issue by gemmaanderson** [MWATelescope/mwa_trigger#12]
The VOEvent parser needs to filter out Swift triggers for which the Swift star-tracker has lost its lock. These are not real events. 

MWA recently triggered on Swift 948244 (8 Jan 2020) for which this was the case. See the following VOEvent:
[VOEvent](http://voeventdb.4pisky.org/apiv1/packet/xml/ivo%3A%2F%2Fnasa.gsfc.gcn%2FSWIFT%23BAT_GRB_Pos_948244-660)

The relevant key word to filter on is:
`<Param name="StarTrack_Lost_Lock" value="true"/>`

The Fermi+Swift handler email read as (I have attached the relevant files from this email)
[log_SWIFT_948244.txt](https://github.com/MWATelescope/mwa_trigger/files/4033438/log_SWIFT_948244.txt)
[schedule_SWIFT_948244.txt](https://github.com/MWATelescope/mwa_trigger/files/4033439/schedule_SWIFT_948244.txt)

> The GRB Fermi+Swift handler triggered an MWA observation for a
> Fermi/Swift GRB at 2020-01-08 00:03:09.579 UTC.
> 
> Details are:
> Trigger ID: SWIFT_948244
> RA:         16:15:10.704 hours
> Dec:        -15:01:53.04 deg
> Error Rad:    0.050 deg
> Result: SUCCESS - observation inserted into MWA schedule
> Errors:
>

**Comment by PaulHancock** [comment]
This should now be fixed. I have tested the update on the example voevent that @gemmaanderson included (thanks!) and it will not trigger, but it will still send a debug message to say why it didn't trigger.

**Comment by PaulHancock** [comment]
Just today there was a trigger that didn't happen because the `StarTrack_Lost_Lock` was triggered by mistake.
The following voevent is what caused the mistake.
[false_positive.txt](https://github.com/MWATelescope/mwa_trigger/files/4068941/false_positive.txt)

**Comment by PaulHancock** [comment]
353abd3 fixes the false positive issue and has updated some of the test_events to do a better job of catching this error.

The problem was that "false" (string) != False (bool).

**Comment by PaulHancock** [comment]
@andreww5au I have merged the master branch into dev-hancock and pushed the results so you should be able to bring these new changes back into the master branch without any worries.
