### ISSUE TITLE
MWA does not repoint on updated Flight positions if INTEG_TIME>2.048s

### ISSUE THREAD

**Issue by gemmaanderson** [MWATelescope/mwa_trigger#13]
The initial set of files show the first Flight Position for Fermi trigger 603098793. In this case the INTEG_TIME = 1.024s

[clear_Fermi_603098793_pos1.txt](https://github.com/MWATelescope/mwa_trigger/files/4196374/clear_Fermi_603098793_pos1.txt)
[log_Fermi_603098793_pos1.txt](https://github.com/MWATelescope/mwa_trigger/files/4196375/log_Fermi_603098793_pos1.txt)
[schedule_Fermi_603098793_pos1.txt](https://github.com/MWATelescope/mwa_trigger/files/4196376/schedule_Fermi_603098793_pos1.txt)
[voevent_pos1.txt](https://github.com/MWATelescope/mwa_trigger/files/4196378/voevent_pos1.txt)

However, the second Flight position had an INTEG_TIME = 4.096s, which meant that the telescope did not repoint at this updated position given that INTEG_TIME > 2.048s

[email_pos2.txt](https://github.com/MWATelescope/mwa_trigger/files/4196393/email_pos2.txt)
[voevent_pos2.txt](https://github.com/MWATelescope/mwa_trigger/files/4196394/voevent_pos2.txt)

The subsequent Ground and Final positions (positions 3 and 4) did not change the pointing of the MWA observation either as they were incorrectly attributed to a different Fermi trigger.

[email_pos3.txt](https://github.com/MWATelescope/mwa_trigger/files/4196395/email_pos3.txt)
[voevent_pos3.txt](https://github.com/MWATelescope/mwa_trigger/files/4196396/voevent_pos3.txt)
[email_pos4.txt](https://github.com/MWATelescope/mwa_trigger/files/4196398/email_pos4.txt)
[voevent_post4.txt](https://github.com/MWATelescope/mwa_trigger/files/4196399/voevent_post4.txt)

See also the Fermi GCN notices at:
[https://gcn.gsfc.nasa.gov/other/603098793.fermi](https://gcn.gsfc.nasa.gov/other/603098793.fermi) 

Given that there is no point in cancelling an observation as we cannot repopulate the schedule with the original observations that were overridden, it makes more sense from a science point of view to accept this subsequent position repoint, even if the event does turn out to be a long GRB (i.e. in INTEG_TIME quantity no longer passes our initial trigger requirement).

**Comment by gemmaanderson** [comment]
Another incident of this occurred this morning - see emails for Fermi_605632577 on 11 March 2020. While the first flight position had INTEG_TIME=1.024s, the second flight position had INTEG_TIME=4.096 so the telescope did not repoint. Luckily when the first ground position came through, the telescope properly repointed.

See the Fermi GCN notices at:
[https://gcn.gsfc.nasa.gov/other/605632577.fermi](https://gcn.gsfc.nasa.gov/other/605632577.fermi)

**Comment by andreww5au** [comment]
Actually, that trigger didn't work at all - I had updated helios from Ubuntu 16.04 to 18.04 on Tuesday. The web services and most of the M&C code were working, but one of the Python packages that schedule_observation.py depends on (h5py) broke in the upgrade.
