### ISSUE TITLE
Update swift GRB triggers to always use VCS for 2020B (Even long ones)

### ISSUE THREAD

**Issue by PaulHancock** [MWATelescope/mwa_trigger#20]
A long GRB observed in VCS mode is going to be a useful observation, and it is not currently in our triggering setup.

In order to catch at least one event in VCS mode in 2020B semester, set the trigger system to respond to all Swift GRB events until we have at least 1 Short GRB observed, and then revert back to only triggering on short GRBs.

**Comment by PaulHancock** [comment]
Also turn off all Fermi triggers for 2021A

**Comment by andreww5au** [comment]
Hi Paul, both of these are done now. I missed this back in October because github emails go to my home address, and I get lots of github emails about repos that I don't have anything to do with. If you need anything changed in mwa_trigger, email me directly.

**Comment by PaulHancock** [comment]
This was more of a reminder to myself, but thanks for the very quick update!
I'll close this now.
