### ISSUE TITLE
Please include credits/acknowledgements

### ISSUE THREAD

**Issue by gemmaanderson** [MWATelescope/mwa_trigger#23]
Could you please add the required credits and acknowledgments to the Readme file? For this project, I would assume that citing [https://ui.adsabs.harvard.edu/abs/2019PASA...36...46H/abstract](https://ui.adsabs.harvard.edu/abs/2019PASA...36...46H/abstract) would be the most appropriate?

**Comment by PaulHancock** [comment]
Done in cd90a62e206c3bea60202acbe756ae0fe3374c2f
